### ISSUE TITLE
ME Fluid Interface slow to receive liquids?

### ISSUE THREAD

**Issue by tgstyle** [ExtraCells/ExtraCells2#137]
It seems the internal tank on the ME fluid interface only sends out 20mB a tick?

**Comment by DrummerMC** [comment]
Now fluid interfaces have the same speed as export/import buses

**Comment by babyblasphemy** [comment]
I might add that sometimes the fluid interface gets stuck when importing fluids. I have a setup importing all different kinds of fluids from a tesseract, but sometimes it gets stuck with 1mb of some fluid in the fluid interface since it won't import it until there are 20 mb in the interface. This is also because the interface imports fluids to internal tanks based off of the side it is coming from, all things coming from below going into the first tank. A regular ME interface will accept items into all 8 slots regardless of what side it is coming from.

**Comment by DrummerMC** [comment]
The fluid interface should do all liquids directly in the system. Only if the system is full it goes in the internal tank from the interface. I think it is a bug.

**Comment by babyblasphemy** [comment]
Well my setup is Liquid XP -> Fluid interface -> Fluid Storage Bus -> Ender IO Experience Obelisk
The Experience Obelisk can store unlimited xp in the form of Liquid XP as far as I know.
