### ISSUE TITLE
Suggestion Crafting Storage

### ISSUE THREAD

**Issue by EntraptaJ** [ExtraCells/ExtraCells2#272]
My idea is crafting storage for the larger storage components, it would be very useful for larger crafting like compressed cobble.

**Comment by UntouchedWagons** [comment]
I agree.

**Comment by jusitnboggs** [comment]
Sorry for the Dupe issue....

**Comment by Armigus** [comment]
Compression crafting/storage similar to the Storage Drawers model would be nice.  Instead of a storage bus on their compacting drawer you would have a specialized compression pattern that recognizes a compression recipe pair, automatically compresses whatever comes in when possible, and decompresses on demand for recipes like furnaces or pistons.  This pattern would go into autocrafting interfaces.

Each compression recipe pair would need its own pattern so cobblestone would need 8 patterns and most metals would need 2 (nugget -> ingot -> block).

**Comment by ruifung** [comment]
theres only one problem with that - AE2 does not deal well with circular dependencies in crafting. Also can already be done with existing patterns.

**Comment by EntraptaJ** [comment]
Man this was a blast from the past.
