### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by ruifung** [ExtraCells/ExtraCells2#274]
This is an issue for code cleanup in this mod.

In trying to fix some bugs, I think that this mod needs a significant cleanup of its code, a few issues I've noticed are 
- Containers do not close when the part / block they are for no longer exist. (Working on this, should fix some of the dupe bugs related to containers gui not being closed after part is wrenched.)
- Missing localizations.
- Lots and lots of bugs. (Or well.. outstanding issues.)
- Code is somewhat messy and poorly commented (There are variables named with obfuscated names?! - In the scala files.)

@M3gaFr3ak @DrummerMC

**Comment by ruifung** [comment]
If anyone doesn't mind, I'm refactoring, rewriting and generally cleaning up the code in my fork.
Also rewriting the java sections in scala since having part of it in scala and part of it in java is... inconsistent.

**Comment by lehjr** [comment]
Honestly, I hoping to see EC merged into AE like mentioned here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/286 even if not in full, but just to have the important bits, like terminals, buses and interfaces, and that's mainly to see the mod continue in a way that is consistent with AE's code quality standards so that the end user has a more fluid experience. I think end users would benefit the most, especially in the next MC version jump. For awhile, I tried to help get things working, then someone else, then someone else, but let's face it, this mod needs a team effort.

**Comment by ruifung** [comment]
Hmm thats not a bad idea. The main reason I'm rewriting it is to generally bring its code quality up.
And yes, this mod needs a team effort indeed. My rewrite branch is progressing.. slowly because I only have limited time to work on this.

Gas support on the other hand, is tricky because there is no standardized gas API... but I understand drummerMC implemented it using the Mekanism API.

**Comment by lehjr** [comment]
And that's the problem, limited time or limited interest, or both, not just on your end but everyone that comes along and goes again. It happens to every project. Merging this mod with AE means that the mod will go on as long as AE does, assuming they're interested. And if so, whatever they don't merge in would still be EC, but with a much smaller and manageable code base and not as critical to end users when the bugs aren't fixed as fast as they should be or updates don't keep pace with AE versions. To me it's a win for everyone, but of course, it's not my decision to make. But from an end user perspective, can you say you'd rather have a half working, bug filled mod or one that fully works?

**Comment by ruifung** [comment]
smaller and more manageable code base? Well... most of EC2's code is either directly or indirectly related to the fluid components. And the gas functionality is just pretty much a bolt on function to the fluid functions. So yes, it would cut down a lot of the code size, although EC would probably be left with almost nothing. Off the top of my head? All thats left without fluid functionality is the various item storage cells. Gas functionality doesn't count because I think it was never completely implemented in the first place.

However, the current state of the code isn't even fit for merging anywhere. If AE wanted to add fluid support? They would just end up recoding everything from scratch.

**Comment by ruifung** [comment]
Although if the fluid function was part of AE, it would easily solve one of the biggest problems that I can't seem to find a solution to yet, seamless support of mixed fluidStack / itemStack recipes for autocrafting. The current implementation in EC has a few flaws, but thats unavoidable as it has to operate within constraints of the AE2 autocrafting subsystem

Maybe @DrummerMC  or @M3gaFr3ak can give their opinions on this matter.

**Comment by lehjr** [comment]
Yes, merging EC components into AE would mean rewriting the code. Actually it would be implementing everything almost entirely from scratch, but even then, coding fluid counterparts of AE's parts from inside AE should be less work than rewriting EC and trying to fix broken things and keep pace with AE changes. As it is, there are currently outstanding bugs that were opened almost a year ago. There would probably be even more if people hadn't given up on EC and moved on. 

I'm not saying that a code cleanup without a merger isn't possible, it's just as you say, coming slowly due to limited time, the same limited time that hinders fixing bugs, adding features, finishing things, keeping up with AE especially when they jump to another MC version. A rewrite, bug fixes, finishing things, adding features... all of that need team effort, more than a team of one and I for one would like to not see this mod go the way of Traincraft, where a planned rewrite turned it into vaporware. The sole remaining developer didn't realize that the ambitions were bigger than the amount of time available until it was too late.

**Comment by ruifung** [comment]
Well that aside, I've been working on the rewrite fairly often. Although I don't work on it every day, I do work on the rewrite at least once a week, mostly more. Although I have to admit most of the time is spent studying the existing code to figure out what it does. 

The majority of work involved in both rewriting and fixing bugs (for me anyway) is trying to figure out what the heck the code in question is doing. I'm aware of the legion of bugs in the bug tracker that hasn't been fixed, but I've been fixing the more recent simple ones. Unfortunately the more complicated ones involving the logic such as dupes are more... challenging to fix as I have to figure out what said code does before I can fix it. 

If anyone wants to help with fixing bugs or anything, feel free to throw a PR.

That aside, this direction of the conversation is going off topic from the actual issue on hand.
