### ISSUE TITLE
Fluid Annihilation Plane stops working

### ISSUE THREAD

**Issue by kadamgreene** [ExtraCells/ExtraCells2#285]
I have a Fluid Annihiliation plane over an infinite source of water.  It filled up a 4k fluid cell, but as I used the water it didn't replenish it.  I actually have to leave the dimension (went to nether) and come back, place a cobble stone under the plane and then break it to make it reload the cell in the me drive.

**Comment by kadamgreene** [comment]
Just FYI:  I replaced the Annihilation plane with a Fluid Transfer Node from Extra Utilities pumping into a Portable Tank and connected a Fluid Import Bus to the tank and it works fine (replenishes what is used)

**Comment by ruifung** [comment]
what about pumping into a fluid interface?

**Comment by jkuball** [comment]
I can't reproduce this behaviour: Because I can't make a reliable infinite water source which is detected by the fluid annihilation plane. It does not react on the most things like buildcraft water sources or even stranger - a fluid formation plane. (But it reacts to user fluid placement via bucket or botania rod of the seas)

This should be fixed, yeah.
