### ISSUE TITLE
Conflict with AE2 buses fail with PneumaticCraft mods gasoline

### ISSUE THREAD

**Issue by iceman11a** [ExtraCells/ExtraCells2#300]
I tried to export some fuel from a fluid export bus to find out that it was seeing gasoline, and not fuel. Even the Buildcaft refinery was making gasoline and not fuel. I had to remove the PneumaticCraft mod. any way for some reason. When I tried to export some fuel. The AE2 network bus didn't see the gasoline as fuel. So sense all I have in the network was fuel. It won't export the fuel (Gasoline) because it doesn't see the fuel is gasoline. 2 different fuels. conflicting with each other. From what I can see that fuel is fuel and gasoline is gasoline. So I don't know or how else to explain this. It's just the conflict with one fuel and the other using AE2 export buses. and BC refinery's.

**Comment by XFactHD** [comment]
BC fuel and PneumaticCraft gasoline are internally both registered as fuel, for the game they are entirely the same fluid.

**Comment by ruifung** [comment]
The fluid handling system in EC2 uses AE2's API's fluid capabilities. In fact, the containers get the Fluid representation from Forge.

@XFactHD  I gather that this issue is because while both of them are registered as the same fluid name, they both have different Fluid representations? 

I gather that the simplest solution would be to have EC normalize all fluid operations to the fluid API registered one?

**Comment by XFactHD** [comment]
@ruifung right, but it shouldn't actually be a problem, in my setup a pneumaticcraft refinery puts out gasoline, it goes through TD ducts as gasoline and the TE resonant tanks convert it to BC fuel which is then imported into the AE system through a fluid interface.
@iceman11a if you can, import the fuel through a TE tank and then you can configure the export bus to export BC fuel and it should work.

**Comment by ruifung** [comment]
I suppose something like the unifyStack method in https://github.com/ExtraCells/ExtraCells2/blob/rewrite/src/main/scala/extracells/common/util/FluidUtil.scala should do the trick?
 Assuming its used to normalize all fluids going into the system? No need for going out though as storage is already normalized due to save / load.

**Comment by XFactHD** [comment]
IIRC this function converts every fluid that is registered under the same name (like in our case with fuel) into the first fluid that got registered under that name. For example if you installed BC first, the fluid would be converted to BC fuel, but if you installed PneumaticCraft first, it would convert the fluid to gasoline.

**Comment by ruifung** [comment]
It does, but on the other hand, that will already happen when the storage cells are saved and loaded from NBT data, as the built in functions that serializes the FluidStack to nbt already does that, specifically the writeToNBT and loadFluidStackFromNBT methods.  This just applies it to incoming fluids as well. - Based on what I can remember offhand, any fluids that is inserted will keep its Fluid definition until the world is reloaded - then it will get converted to the first registered Fluid under that name.

**Comment by iceman11a** [comment]
@XFactHD So what your saying is that if I use a TE tank, Any tank from that mod and import it into that tank, and then export it from that tank to what ever. It then will be BC Fuel. Here's the other problem. If I put this mod back on my server and client it will turn all the BC Fuel I have to gasoline. where the export bus will not know what gasoline is and fail. So how would I do this for all the fuel I all ready have made. 

The last thing is that gasoline and fuel are not the same FUELS. The work in any thing you want them to work in. Not the same. 1) different colors. for one thing. When can we expect a fix for the fluid export bus.

**Comment by ruifung** [comment]
There is no way to handle it. Gasoline and BC fuels are registered under the same name in the Forge Fluid Registry. - There is NO way to get the alternative registrations just by the name alone. The problem here is that pneumatic craft is testing against its specific Fluid instead of the one that is default in the Fluid Registry.

Not to mention that the default saving to and loading from NBT data for FluidStacks will also cause this behavior.

What I _probably_ can do is make it convert any compatible liquids to the one specified in the configuration, but then I have no idea how to save the data as , like stated above - the Fluid Registry only returns the default Fluid.

**Comment by ruifung** [comment]
@iceman11a It appears that your issue with gasoline is resolved in PC 1.11.8 and newer.

Leaving this issue open because I plan to add that normalizing code to ensure that the EC2 grid will always use the default fluid.

**Comment by iceman11a** [comment]
@ruifung Thanks. That fixed it.

**Comment by iceman11a** [comment]
from what I can see. No matter what I do. it seems that the BC Fuel is gone. I can't make that any more. It seems that the refinery's only make gasoline. So I guess BC Fuel can't be made any more. So I guess I won't need the BC fuel any more.

**Comment by ruifung** [comment]
If you have any of said fluids saved in EC2, it _should_ automatically change to whatever fluid is registered to that name first.

**Comment by iceman11a** [comment]
Well I mean is that other mods all so use the fuel from BC. Will those's mods be able to use it all so. So I get the idea that the Buildcraft fuel is no longer needed. Sense I don't have any thing to make it with.

**Comment by XFactHD** [comment]
BTW, PneumaticCraft is not the only mod registering their fuel as BC fuel.

**Comment by ruifung** [comment]
All fluids registered under the same name is probably supposed to be interchangable.

**Comment by XFactHD** [comment]
Right. I think for BC fuel, the main point is to be able to burn any fuel in any generator that is compatible with BC fuel without needing compatibility code for every mod.

**Comment by ruifung** [comment]
If mod's would just stop using their own Fluid's when the FluidRegistry fails to register it as the default and uses the default Fluid from the FluidRegistry?, It would probably have less issues =P

**Comment by XFactHD** [comment]
This seems to be the same problem with modders doing something they shouldn't or the other way around as BluSunrize mentioned in one of his commits for canFill and canDrain checks.

**Comment by iceman11a** [comment]
I'll I need now is a car I can use this gasoline in. lol. Ok, thanks guys.
