### ISSUE TITLE
Unable to import Gelid Cryotheum into ME system

### ISSUE THREAD

**Issue by jmcaffee** [ExtraCells/ExtraCells2#303]
FTB Infinity on MC 1.7.10. Extra Cells 2: ExtraCells-1.7.10-2.2.73b129

I've added a 16k Fluid Storage module to a ME Drive, and a ME Fluid Import Bus to a smart cable connected to my controller. When I place a Extra Utilities drum full of Gelid Cryotheum next to (on on) the import bus, no liquid is imported into the system.

I've also tried priming the import bus with a bucket of cryo, With no luck.

Additionally, I've piped cryo from the drum into a Certus Quartz tank, and attempted to import from the tank with no results.

I've verified I have a channel for the import bus; it lights up and waila says 'Device Online'.

What am I doing wrong?

**Comment by ruifung** [comment]
Can you try again with the latest build from the jenkins?

**Comment by Armigus** [comment]
I'm having a similar problem with Forestry's fruit juice.  I even went so far as to use the Fluid Terminal to but a bucket into the system.  After that I tried a lava bucket thinking you had issues recognizing the fluid dictionary.  No dice there either.  The AE system might be blind to the fluid drive.  If you want us to try a Jenkins build please post the link.

Follow-up.  A storage bus on a bedrockium drum works, allowing a terminal to see it and export to a buffer drum I'm using for fermenters.  The storage cell is the issue here.  Please check.

**Comment by leagris** [comment]
Same problem with gregtech 5
fluid.liquid_heavy_fuel cannot be stored in Fluid Cell
