### ISSUE TITLE
AE2 RV4

### ISSUE THREAD

**Issue by p455w0rd** [ExtraCells/ExtraCells2#428]
You're not on IRC, I don't know how else to get in touch with you. Just wondering if you've started porting or plan to port to RV4. I'll be starting my port of Wireless Crafting Terminal in a couple days. If you do not plan to support RV4, I'd like to chat with you :)

**Comment by shartte** [comment]
Yo, please feel free to reach out to me on IRC. You sadly missed me (probably timezone related).
We currently don't have the API "open", since we still want to make breaking changes to it before we go to beta. One example would be that we are thinking about making IGridHost capability based. 
Do you have any specific grievances with the AE2 API that you would like to see resolved in rv4? This is now the unique chance to make those changes.

**Comment by ghost** [comment]
I didn't understand. Will you rewrite ExtraCells2 on 1.10.2?

**Comment by DrummerMC** [comment]
I will be portet on 1.10.2

**Comment by Miner94** [comment]
any idea how far along this is

**Comment by p455w0rd** [comment]
FAR..lol..i'll be making some PRs soon to finish 1.10, then...1.12 here we come :) Just so you know, @Nedelosk is responsible for the 1.10 port up to this point. I will be working with him via PRs :)

**Comment by Miner94** [comment]
alright cool i just hope there is a usable download soon this is literally all i'm waiting for lol
