### ISSUE TITLE
ME Fluid Assembler Stalls with Pam's Harvestcraft Recipes

### ISSUE THREAD

**Issue by wylderhoads1809** [ExtraCells/ExtraCells2#429]
When trying to convert water into fresh water the fluid assembler get's stuck until I remove and replace a section of glass cable, at which point it resumes. The same thing happens with milk to fresh milk.

![2016-10-20_00 41 53](https://cloud.githubusercontent.com/assets/22950512/19546515/597f1a80-965e-11e6-8653-7752e9e70474.png)
![2016-10-20_00 41 57](https://cloud.githubusercontent.com/assets/22950512/19546516/597f2d18-965e-11e6-8ce4-a5499328f5c2.png)
![2016-10-20_00 42 03](https://cloud.githubusercontent.com/assets/22950512/19546520/59840da6-965e-11e6-87f5-27bde333e10d.png)
![2016-10-20_00 42 07](https://cloud.githubusercontent.com/assets/22950512/19546519/5983fa46-965e-11e6-9f0e-a169b0148e41.png)
![2016-10-20_00 42 10](https://cloud.githubusercontent.com/assets/22950512/19546518/5980e6b2-965e-11e6-9c3f-e028f7f98297.png)
![2016-10-20_00 42 11](https://cloud.githubusercontent.com/assets/22950512/19546517/597fe3a2-965e-11e6-9463-b5b467801f3c.png)
![2016-10-20_00 42 12](https://cloud.githubusercontent.com/assets/22950512/19546524/598a2240-965e-11e6-9f4d-fbc19c677af8.png)
![2016-10-20_00 41 08](https://cloud.githubusercontent.com/assets/22950512/19546521/5984dcae-965e-11e6-835e-d9fada75801d.png)
![2016-10-20_00 41 16](https://cloud.githubusercontent.com/assets/22950512/19546522/598798b8-965e-11e6-991a-80166dd53d65.png)
![2016-10-20_00 41 26](https://cloud.githubusercontent.com/assets/22950512/19546523/5988d660-965e-11e6-82e8-90e40abde1b0.png)
![2016-10-20_00 41 31](https://cloud.githubusercontent.com/assets/22950512/19546525/598bbd8a-965e-11e6-9ea4-1f60b8c17bd7.png)
![2016-10-20_00 41 39](https://cloud.githubusercontent.com/assets/22950512/19546526/598cd67a-965e-11e6-99a6-5fa8321d93a4.png)
![2016-10-20_00 41 44](https://cloud.githubusercontent.com/assets/22950512/19546527/598d42a4-965e-11e6-8ced-373d1ec2ceed.png)
![2016-10-20_00 41 47](https://cloud.githubusercontent.com/assets/22950512/19546528/598e27b4-965e-11e6-885c-0f1236e9a151.png)

**Comment by Nividica** [comment]
**Edit:** Further testing shows that any other fluid recipe in the same assembler causes the craft to stall.
This leads to a **work-around** for the issue, if you dedicate a fluid assembler to the fresh milk recipe, it will work as intended.

I can confirm this issue still exists with milk, the water -> fresh water recipe works without issue.
As @wylderhoads1809 suggested, causing a grid update kickstarts the assembler.

I wanted to make a minimum reproducible setup and made some discoveries along the way:
## Conditions
1) If the only known fluid recipe is the `milk bucket -> 4 x fresh milk` recipe, the craft succeeds.
2) If there is another fluid recipe in the same assembler, the craft stalls.
3) Attempting a grid update without a `ME interface` somewhere on the network will not cause the craft to resume
4) Causing any grid update with a `ME interface` somewhere on the network will cause the craft to resume.
5) A grid update can be triggered with a `toggle bus` or its inverted counterpart, connected to a simple network part, such as a terminal.

## Minimum Setup
### Blocks
Pattern Terminal
Fluid Terminal
Drive
1k Crafting Storage
Fluid Assembler
ME Interface
Inverted Toggle Bus
Button
Glass Cable
Energy Cell

### Items
1k Fluid Cell
1k Storage Cell
Pot, Pam's Harvest
2x Blank Pattern
Milk Bucket(s)
Fresh Milk

### Steps
1) Build the setup as shown in the following picture
![extracellsmilksetup](https://user-images.githubusercontent.com/1585989/34705844-6e9b4fec-f4d1-11e7-8957-b08f9ea55287.png)

2) Encode the pattern `Milk bucket -> 4x Fresh Milk`
3) Encode the pattern `Milk bucket + Pot -> Plain Yogurt`
4) Place both patterns in the `Fluid Assembler`
5) Add milk to the fluid system via the `Fluid Terminal`
6) Request `Fresh Milk` from the pattern terminal.
7) -- Crafting Hangs --
8) Click the button, which will temporarily remove the `Pattern Terminal` from the grid, causing an update.
9) -- Crafting Resumes -- 

## Thoughts
As to why the interface is required to be present on the network during a grid update, I suspect the grid update is cascading into a crafting patterns update because of the interface, and that in-turn causes the fluid assembler to reevaluate its crafting status.
This is the only fluid recipe that has given me any trouble, however I can not come up with any reason this one in particular causes an issue.
I thought it may have something to do with producing multiple results, however other milk bucket recipes that produce multiple results work.
Next I thought it may have something to do with the simplicity of the conversion, so I tested `Water Bucket -> Fresh Water` and that works, so I also included another of Pams recipes `Water Bucket + Pot -> Salt`, and those work as well.
I have no idea what makes the milk recipe unique, but I am hoping with this report that finding the root cause of the issue will be made easier.
I have not performed a test with only Extra Cells and Pams Harvestcraft, all tests were performed within FTB Revelation.

## Environment
Version: `ExtraCells-1.12.2-2.5.10a47`
Modpack: `FTB Revelation`
Java: 8
