### ISSUE TITLE
pattern crash in 1.10

### ISSUE THREAD

**Issue by Trinsdar** [ExtraCells/ExtraCells2#469]
when I placed a normal pattern that had a recipe using a water bucket in the fluid interface the game immediately crashed.

Crash report: https://pastebin.com/W0pdQjBK

minecraft version: 1.10.2
forge version: 1.10.2-12.18.3.2422
Ae2 version: rv4-stable-1
Extra cells 2 version: 2.4.2aNIGHTLY

there are a couple other mods, but they don't effect the crash.

**Comment by abdullamu** [comment]
Same here crashes I hope it get fixed because it seems important.

**Comment by abdullamu** [comment]
Forgot to mention I'm playing on 1.12.2 latest EC2

**Comment by DrummerMC** [comment]
Can you upload a crashreport for the 1.12.2 version pls

**Comment by abdullamu** [comment]
sure thing here you go 

https://pastebin.com/muj8U8r3

**Comment by abdullamu** [comment]
now i cannot load the world, i can start the game but the world crash the game with this in the console

https://pastebin.com/ysYy6ubj

it seems the pattern keep crashing the game. so i cannot play until this issue is fixed. :(

**Comment by abdullamu** [comment]
Is it difficult to fix ? Whats the problem if I may ask just curious to know if I should remove the mod or wait for fix.

**Comment by DrummerMC** [comment]
I think I will fix it the next hours

**Comment by abdullamu** [comment]
thank you kindly sir. :)

**Comment by DrummerMC** [comment]
are you placing the interface in the same ec version?

**Comment by DrummerMC** [comment]
donload the latest version from [here](https://ci.appveyor.com/project/DrummerMC/extracells2/build/1.0.44/artifacts) and tell me if it works

the build will take a few minutes

**Comment by abdullamu** [comment]
everything works fine now. the world load and no crash. thank you 
but there's few questions i hope you dont mind answering.

i just found out that the fluid assemble is the one that you place the pattern in it to craft unlike AE which needs interface. if thats the case why do interface accept  pattern whats the usability of it ?

second thing is since 2 builds ago i started to get notification in the chat about EC2 support ingame guide click here to download, when i press on it it gives error preforming the task. nothing mention that even the web page in curse doesnt mention that theres guide or where i can download it?.

**Comment by abdullamu** [comment]
plus when i have 6 buckets of fluids and request craft that need 7 buckets theres no error mentioning that i need 1 more it just accept it and stays on scheduled craft plus it doesn't mention which liquid are used. 
so if you have huge crafting task you have to babysit it and check how many since it doesnt even tell you how much buckets are needed for the operation.  is this intended or bug in the system ?

**Comment by DrummerMC** [comment]
I can't tell ae that I need 7 buckets for the autocrafting. The API only supports IAEItemStack not IAEStack

**Comment by DrummerMC** [comment]
you can download the ingame wiki mod from https://minecraft.curseforge.com/projects/in-game-wiki-mod

example pattern for the fluid interface placed ner a fluid transposer
input:
- empty bucket
- water bucket
output:
- water bucket

The system will insert all items that are not a filled fluid container (in the example the empty bucket) in the fluid transposer. The fluid interface replace all filled containers (in the example the water bucket) with the contained fluid (in the example 1000 mB water). The fluid transposer will fill the water into the bucket and an import bus can import it into the ae network

**Comment by abdullamu** [comment]
thank you very much for the help :)
