### ISSUE TITLE
[1.12.2]  known bugs

### ISSUE THREAD

**Issue by Cazadorsniper** [ExtraCells/ExtraCells2#472]

**Comment by Cazadorsniper** [comment]
Me Drive Fixture and Blast Resistant Drive delete drives within them.
Me Drive Fixture won't visually display drives in it if there is another fixture next to it that is not full.

**Comment by DeadSix27** [comment]
Yueh actually asked you on TheRealp455w0rd's discord if you even take bug reports yet.. but since @Cazadorsniper took the initiative

Here's my observations (I tested on: https://github.com/ExtraCells/ExtraCells2/commit/7a3f4cf0658cbd0d8fab112814b56b4011ab96b3 )

EDIT:
I separated the issues into their own issue posts now.

**Comment by DrummerMC** [comment]
fixed fluid assembler client crash and shift-right clicking Gas/Fluid cells

**Comment by DrummerMC** [comment]
fixed client crash on shift-click in hard me drive
Ore Dict Export Bus works
Gas Terminal fixed (only fill container if it is empty)

**Comment by DeadSix27** [comment]
@DrummerMC I can make all the issues separate if you prefer that, (also I added 1 more to the bottom)

**Comment by DrummerMC** [comment]
You can make separate issues

**Comment by DeadSix27** [comment]
@DrummerMC Done, feel free this close this issue as everything in here is in a own issue post now
