### ISSUE TITLE
Crash With WCT + AE2WTLib + Baubles

### ISSUE THREAD

**Issue by gggg336** [ExtraCells/ExtraCells2#619]
Extra Cells: 2.6.1a
Wireless Crafting Terminal: 3.11.83
AE2WTLib: 1.0.2 (New library for WCT that is required for the new version of WCT)
Baubles: 1.5.2
AE2: RV6 Stable 4
Forge: 2776

Integration option in Extra Cells for WCT has been tried with it on and off. Reverting WCT version will not result in crash.

https://paste.ee/p/ijXXQ

**Comment by p455w0rd** [comment]
yeah..i gotta update EC2 now and remove the WCT support..this functionality will be handled via my library (AE2 Wireless Terminal Library) going forward..thanks for the report tho

**Comment by p455w0rd** [comment]
i am a little confused though...no idea why extracells would be referencing baubles..gotta be something about Scala I'm not understanding as to why it's doing this..I was suspecting it was due to the `isWirelessCraftingEnabled()` method I removed from the WCT api...but this is referencing baubles from the universal terminal...weird

**Comment by BrockWS** [comment]
ItemWirelessTerminalUniversal -> CraftingTerminal -> IWirelessCraftingTerminalItem -> ICustomWirelessTerminalItem -> IBaubleItem

Since IWirelessCraftingTerminalItem now extends ICustomWirelessTerminalItem, EC2 now needs to implement the IBaubleItem interface method(s)

**Comment by Pival81** [comment]
I tried building the mod with #622, but I still crashed with the same error.
Has anyone got it to work?

**Comment by BrockWS** [comment]
Can you verify you are using the latest version of WCT & Wireless Terminal Library & PWLib. If its still happening please post a pastebin link with the crashlog. You could also try this instead of building it yourself. https://ci.brock.pw/job/ExtraCells2/job/ExtraCells2-PRs/5/

**Comment by CrankySupertoonArchive** [comment]
Just as a reminder the new build should be on curse

**Comment by Xhale1** [comment]
I haven't seen a new update on Curse for Extra Cells that fixes the issue. I've got the same crash with Baubles 1.5.2, AE2 RV6 stable 6, Extra Cells 2 2.6.1a, and WCT 3.11.86

**Comment by mr2013** [comment]
> If its still happening please post a pastebin link with the crashlog.

Google returns this issue when searching for '"Method extracells" "is abstract".' However, OP used a pastebin that helpfully deleted their paste after a short period of time, so apologies if this is a different bug.

I'm in the same boat as Xhale1. The crash for me still happens when a player has the wct in a bauble slot, and also when observing another player with the wct in baubles. This is using the latest released versions of all related mods. Editing the player's nbt file to remove the wct gets the game to a playable state again.

Formatted: https://paste.dimdev.org/sixayupoye.mccrash
Plaintext: https://pastebin.com/sApz6BJh

**Comment by eddoww** [comment]
Just ran into this issue myself, running latest versions of "Extracells2, applied energistics, wirelesscraftingterminal". Is there a fix out yet?

**Comment by NyxCode** [comment]
I'm having the same problem here, running FTB Revelation with the newest EC2 version. Is there still no fix available?

**Comment by TheInfamousAlk** [comment]
Still having this issue, everything listed above is up to date.
