### ISSUE TITLE
[1.12.2] Start up crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [ExtraCells/ExtraCells2#644]
Hi,
I wanted to install EC2 in my modpack, but I got a crash.

https://paste.dimdev.org/facowutala.mccrash

MC: 1.12.2
EC2: 2.6.2a
AE2: rv6 - stable 6
Forge: 2821

More mods you can find in the crash log.
If I remove EC2 -> all is okay.

Edit: I found the mod, which causes the crash -> Applied Integrations.
I create a comment under the curse page and I link this Github issue. :)

**Comment by indiscrete-void** [comment]
o.m.g.... SO many crashes caused by only null sprite for texture of one liquid from my mod, which emulates energy for Ae2's storage channel ;(

This issue is only caused by my mod, **please ignore this issue, and close**. As i already sayed in #11 from my issue tracker (https://github.com/AzazeII/Applied-Integrations/issues/11) I will fix it in new version of my mod

**Comment by indiscrete-void** [comment]
Fixed

**Comment by TheSnowyChickens** [comment]
Thx^^
